version: '2'

services:

  project-clara-angular:
    build:
      context: ./project-clara-client
      dockerfile: ./.docker/project-clara-angular.development.dockerfile
    command: ng serve --host 0.0.0.0 --port 4200
    container_name: project-clara-angular-serve-dev
    image: project-clara-angular
    networks:
      - dev-network
    ports:
      - '4200:4200'

networks:
  dev-network:
    driver: bridge
