version: '2'

services:

  propelling-angular:
    build:
      context: ./propelling-client
      dockerfile: ./.docker/propelling-angular.production.dockerfile
    command: ng build --prod --aot=false
    container_name: propelling-angular-build-prod
    image: propelling-angular
    networks:
      - prod-network
    volumes:
      - ./propelling-client/dist:/home/app/propelling/dist

  propelling-nginx:
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT' < /etc/nginx/conf.d/propelling.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    container_name: propelling-nginx-prod
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    image: nginx
    networks:
      - prod-network
    ports:
      - '8080:80'
    volumes:
      - ./propelling-client/.docker/nginx.conf:/etc/nginx/conf.d/propelling.template
      - ./propelling-client/dist:/var/www/propelling

    sample-app:
      build:
        context: ./propelling-server/sample-app
        dockerfile: ./.docker/sample-app.production.dockerfile
      command: java -jar ./target/app.jar
      container_name: sample-app-serve-prod
      image: sample-app
      networks:
        - prod-network
      ports:
        - '9000:9000'

networks:
  prod-network:
    driver: bridge
